WIP: implement websocketed notifications for new RFIDs
youagree/human-entry-control pull request #15
Opened 2021-02-12 10:10 UTC by youdzinn

добавлено:
* вебсокет endpoint 
* оповещение об ошибках при получении меток
* параметризация входящего запроса POST /v1/event, принимается следующий объект
```json
{
   "device_id": long,
   "rfid": string
}
```

2021-02-12 10:54 UTC, youdzinn commented on car-entry-control-impl/pom.xml
> +        </dependency>
это выпилить

2021-02-12 10:55 UTC, youdzinn commented on car-entry-control-impl/src/main/java/ru/unit_techno/car_entry_control/stompwebsocket/NewRfidLabelController.java
> +public class NewRfidLabelController {
данный класс вероятно не нужен, поресерчить, будут ли работать оповещения без него

2021-02-13 20:52 UTC, youdzinn commented on car-entry-control-impl/src/main/java/ru/unit_techno/car_entry_control/stompwebsocket/NewRfidLabelController.java
> +public class NewRfidLabelController {
Как выяснилось, методы, аннотированные @MessageMapping, нужны для того, чтобы реагировать на факт принятия сообщения от клиента, например выслать что-то в ответ, в топик, указанный в аннотации @SendTo.
Это в данный момент не требуется.

2021-02-15 17:31 UTC, youagree requested changes

2021-02-15 17:31 UTC, youagree commented on car-entry-control-impl/src/main/java/ru/unit_techno/car_entry_control/service/EventService.java
> +            brokerMessagingTemplate.convertAndSend(
мб вынести в отдельный прайват метод, а то по логике не связано с check и отдельно в кетч обернуть и по семантике обработать

2021-02-15 17:35 UTC, PavelSoldatov commented on car-entry-control-impl/src/main/java/ru/unit_techno/car_entry_control/dto/request/RfidEntry.java
> +    @JsonProperty("device_did")
Опечатка как я понял, device_id должно быть

2021-02-15 17:38 UTC, youdzinn commented on car-entry-control-impl/src/main/java/ru/unit_techno/car_entry_control/service/EventService.java
> +            brokerMessagingTemplate.convertAndSend(
вынес бы в некоторый WSNotifierImpl, у которого есть зависимость brokerMessagingTemplate

2021-02-15 17:38 UTC, youdzinn commented on car-entry-control-impl/src/main/java/ru/unit_techno/car_entry_control/dto/request/RfidEntry.java
> +    @JsonProperty("device_did")
да, поправлю

2021-02-23 18:15 UTC, PavelSoldatov approved these changes

2021-02-23 18:15 UTC, youdzinn commented on car-entry-control-impl/src/main/java/ru/unit_techno/car_entry_control/service/EventService.java
> +            brokerMessagingTemplate.convertAndSend(
пока в отдельном сервисе

2021-02-23 18:18 UTC, PavelSoldatov approved these changes

2021-02-23 18:25 UTC, youagree approved these changes

2021-02-23 18:25 UTC, merged